#!/usr/bin/env php
<?php require __DIR__.'/vendor/autoload.php';

use Crontab\Job;
use Crontab\Crontab;
use Cron\FieldFactory;
use Phron\Processor\Entries;
use Phron\Processor\Generator;
use Symfony\Component\Console\Application;
use Phron\Command\AddCommand;
use Phron\Command\ShowCommand;


/*--------------------
 | Spawn objects
 | -------------------
 */
$job          = new Job;
$crontab      = new Crontab;
$generator    = new Generator($job);
$entries      = new Entries($crontab);
$fieldFactory = new FieldFactory;
$addCommand   = new AddCommand($entries, $generator, $fieldFactory);
$showCommand  = new ShowCommand($entries, $generator, $fieldFactory);

$app = new Application('Phron', '0.1');


/*--------------------
 | Add them to the app
 | -------------------
 */
$app->add($addCommand);
$app->add($showCommand);


/*--------------------
 | Start the app
 | -------------------
 */
$app->run();