#!/usr/bin/env php
<?php

/*--------------------
 | Autoload files
 | -------------------
 */
require __DIR__.'/vendor/autoload.php';




use Crontab\Job;
use Symfony\Component\Console\Application;
use Phron\Processor\Entries;
use Phron\Command\AddCommand;
use Phron\Processor\Generator;




/*--------------------
 | Spawn objects
 | -------------------
 */
$job        = new Job;
$generator  = new Generator($job);
$entries    = new Entries($generator);
$addCommand = new AddCommand($entries);
$app        = new Application('Phron', '0.1');




/*--------------------
 | Add them to the app
 | -------------------
 */
$app->add($addCommand); // add the interactive shell




/*--------------------
 | Start the app
 | -------------------
 */
$app->run();