#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php'))
{
    require __DIR__.'/../../autoload.php';
}
else
{
    require __DIR__.'/vendor/autoload.php';
}

use Crontab\Crontab;
use Crontab\CrontabFileHandler;
use Cron\FieldFactory;
use Phron\Processor\Entries;
use Phron\Processor\JobBuilder;
use Symfony\Component\Console\Application;
use Phron\Command\AddCommand;
use Phron\Command\ShowCommand;
use Phron\Command\DeleteCommand;
use Phron\Command\ExplainCommand;
use Phron\Command\DumpCommand;


/*--------------------
 | Spawn objects
 | -------------------
 */
$crontab            = new Crontab;
$crontabFileHandler = new CrontabFileHandler;
$jobBuilder         = new JobBuilder;
$fieldFactory       = new FieldFactory;
$entries            = new Entries($crontab, $crontabFileHandler);

$addCommand         = new AddCommand($entries, $jobBuilder, $fieldFactory);
$showCommand        = new ShowCommand($entries, $jobBuilder, $fieldFactory);
$deleteCommand      = new DeleteCommand($entries, $jobBuilder, $fieldFactory);
$explainCommand     = new ExplainCommand($entries, $jobBuilder, $fieldFactory);
$dumpCommand        = new DumpCommand($entries, $jobBuilder, $fieldFactory);

/*--------------------
 | Add them to the app
 | -------------------
 */
$app = new Application('Phron', '0.1');
$app->add($addCommand);
$app->add($showCommand);
$app->add($deleteCommand);
$app->add($explainCommand);
$app->add($dumpCommand);

/*--------------------
 | Start the app
 | -------------------
 */
$app->run();
